import { ChatGroq } from "@langchain/groq";
import { MemorySaver } from "@langchain/langgraph";
import { StateGraph, START, END, Annotation } from "@langchain/langgraph";
import * as readline from "readline";
import nodeMailer from "nodemailer";
import "dotenv/config";


//terminal input setup
const rl = readline.createInterface({
    input:process.stdin,
    output:process.stdout
});

const askQuestion = (query) => new Promise((resolve) => rl.question(query, resolve));

//1. setup llm
const llm = new ChatGroq({
    apiKey:process.env.GROQ_API_KEY,
    model:"openai/gpt-oss-120b",
    temperature:0.2
});

//2. Email transporter setup(nodemailer)
const transporter = nodeMailer.createTransport({
    service:'gmail',
    auth:{
        user:process.env.EMAIL_USER,
        pass:process.env.EMAIL_PASS,
    }
});

//3. define graph state
const GraphState = Annotation.Root({
    recipient_email:Annotation(), //target email address
    topic:Annotation(), // topic of the email
    drafted_email:Annotation(), //email content generated by AI
});

//4. Nodes (worker)

//node A: ai email drafter
async function drafterNode(state){

    console.log("\n [Ai drafter]: Writing professtional email for -> ", state.topic,"\n");
    const prompt = `Write a short , professtional email body (no subject line ) about this topic :${state.topic}`;
    const response = await llm.invoke(prompt);
    
    return {drafted_email: response.content};

}

//node B: email sender
async function senderNode(state){

    console.log("Sending email...\n");
    try {
        const mailOptions ={
            from:process.env.EMAIL_USER,
            to:state.recipient_email,
            subject:"AI Automated Message", //mail subject
            text:state.drafted_email,
        };

        const info = await transporter.sendMail(mailOptions);
        console.log(`[Success] email officially send to : ${state.recipient_email}...\n `);
        console.log(`Message ID: ${info.messageId}`);
        
        
    } catch (error) {
        console.log("Error: ",error.message );
        
    }
    return {};

}

//build the graph
const memory = new MemorySaver();

const workflow = new StateGraph(GraphState)
    .addNode("drafter", drafterNode)
    .addNode("sender", senderNode)
    .addEdge(START, "drafter")
    .addEdge("drafter", "sender")
    .addEdge("sender", END)



//interrupt before send 
const app = workflow.compile({
    checkpointer:memory,
    interruptBefore:["sender"]
});



async function main(){

    console.log("everything is ok!");
    rl.close()

}
main().catch(console.error)