import { ChatGroq } from "@langchain/groq";
import { MemorySaver, Topic } from "@langchain/langgraph";
import { StateGraph, START, END, Annotation } from "@langchain/langgraph";
import * as readline from "readline";
import nodeMailer from "nodemailer";
import "dotenv/config";
import { resolve } from "dns";

//terminal input setup
const rl = readline.createInterface({
    input:process.stdin,
    output:process.stdout
});

const askQuestion = (query) => new Promise((resolve) => rl.question(query, resolve));

//1. setup llm
const llm = new ChatGroq({
    apiKey:process.env.GROQ_API_KEY,
    model:"openai/gpt-oss-120b",
    temperature:0.2
});

//2. Email transporter setup(nodemailer)
const transporter = nodeMailer.createTransport({
    service:'gmail',
    auth:{
        user:process.env.EMAIL_USER,
        pass:process.env.EMAIL_PASS,
    }
});

//3. define graph state
const GraphState = Annotation.Root({
    recipient_email:Annotation(), //target email address
    Topic:Annotation(), // topic of the email
    drafted_email:Annotation(), //email content generated by AI
});


async function main(){

    console.log("everything is ok!");
    rl.close()

}
main().catch(console.error)