import { ChatGroq } from "@langchain/groq";
import { tool } from "@langchain/core/tools";
import "dotenv/config";
import * as rl from "readline";
import * as fs from "fs/promises"
import {z} from "zod";
import { createReactAgent } from "@langchain/langgraph/prebuilt";
import { exec } from "child_process";
import { promisify } from "util";


const execPromise = promisify(exec);

const readline = rl.createInterface({
    input: process.stdin,
    output: process.stdout,
});

//setup llm
const llm = new ChatGroq({
    apiKey: process.env.GROQ_API_KEY,
    model: "openai/gpt-oss-120b",
    temperature: 0.2
});

//2. define tool 
//a. create and write file
const createFileTool = tool(
    async ({ file_name, content }) => {
        console.log(`\n[tool]: Creating file: ${file_name}...\n`);
        try {
            await fs.writeFile(file_name, content, "utf-8");
            return `Success: file ${file_name} created successfully.`;
        } catch (error) {
            return `[Error]: ${error.message}`;

        }

    },
    {
        name: "create_file",
        description: "Creates a  new file and overwrites an existing file with code or text.",
        schema: z.object({
            file_name: z.string().describe("name of the file like -> index.html, script.js, my.txt etc."),
            content: z.string().describe("the full code or text to write inside the file."),
        })
    }
);

//b. readfile
const readFileTool = tool(
    async ({file_name}) => {
        console.log(`\n[Tool]: reading file: ${file_name}...`);
        try{
            const content = await fs.readFile(file_name, "utf-8");
            return `read file success : file name : ${file_name}, content: ${content}`;
        }catch(error){
            return `[error] : ${error}`
        }
    },
    {
        name:"read_file",
        description:"Reads the content, code of an existing file.",
        schema: z.object({
            file_name: z.string().describe("name of the file example -> script.js, index.html, my.txt")
        })
    }
)

//c. execute command/ run code on termial
const executeCommandTool = tool(
    async ({command}) => {
        console.log(`\n [Tool] : Execute command on termial : '${command}...`);
        try {
            const {stdout, stderr} = await execPromise(command);
            if (stderr) {
                return `Command executed but with stderr warnings:\n${stderr}\nFix it if necessary.`;
            }

            return `command execution Success Output: ${stdout}`;
        } catch (error) {
            return `[Error]: ${error}`;
        }
        
    },
    {
        name: "execute_command",
        description:"Executes terminal commands like - node script.js, start index.html",
        schema: z.object({
            command: z.string().describe("commands like -> node script.js, python script.py, start index.thml")
        })
    }
);

const tools = [createFileTool, readFileTool, executeCommandTool];

//3. system prompt 
// 3. System Prompt (The strict brain of the AI)
const systemMessage = `You are a Senior Autonomous Developer AI with full file system and terminal access. 
Your goal is to complete the user's task efficiently without expecting them to do the manual work.

STRICT RULES:
1. NO DUPLICATES: ONLY create ONE file per request unless explicitly asked for more. Smartly guess extensions (e.g., .js).
2. SELF-CONTAINED CODE: When writing code, ALWAYS include default test cases or example calls inside the code itself so it produces an output immediately when run (do not rely on command-line arguments unless asked).
3. MANDATORY EXECUTION: After creating or updating a file, you MUST ALWAYS use the 'execute_command' tool to run it. NEVER present the code to the user without executing it first.
4. SELF-HEALING: If execution fails or throws an error, you MUST read the error, rewrite/fix the code using 'create_file', and execute it again until it runs successfully.
5. FINAL RESPONSE: In your final answer to the user, you MUST show the output generated by the terminal execution. Do not tell the user to run it themselves.
note: html files run the 'start' command! 
`;


//4. create the langgraph reAct agent
const agent = createReactAgent({
    llm:llm,
    tools:tools,
    messageModifier:systemMessage

})

async function main() {

    console.log("FileSystem(developer) agent is ready!...\n");

    readline.question("You: ", async (userInput) => {

        if(userInput.toLowerCase() === "exit"){
            console.log("BYE!");
            rl.close();
            return;
        }

        console.log("\nAgent is thinking/working wait...");
        
        try {
            const response = await agent.invoke({
                messages:[{
                    role:"user",
                    content:userInput
                }]
            });

            console.log("\n[Agent final Response]: \n");
            console.log(response.messages[response.messages.length - 1].content);
            
        } catch (error) {
            console.log("[Error]:", error.message);
            
        }

        readline.close();
    });
}

main().catch(console.error)